language: rust
rust:
    - nightly
    - stable

cache:
  cargo

install:
  - export CXX="g++-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports     # recent version of cmake
    packages:
    - gcc-4.8
    - g++-4.8       # required to compile glslang
    - clang
    - cmake
    - cmake-data

script:
    - cargo test --all -j 1
